import "./style.css";
import { OpenEyeTrack } from "./core/OpenEyeTrack";
import { FaceFeatureTracker } from "./features/FaceFeatureTracker";
import { LandmarkOverlay } from "./features/LandmarkOverlay";
import { extractEyeHeadFeatures, type EyeHeadFeatures } from "./features/EyeHeadFeatures";
import type { EyeTrackingSample } from "./types/Sample";
import { CalibrationController, type CalibrationConfig, type CalibrationPointCount, type TargetShape } from "./calibration/CalibrationController";
import type { GazeModelType } from "./calibration/GazeModels";
import { AdaptiveGazeFilter } from "./gaze/AdaptiveGazeFilter";
import { HeadMovementGuard, type HeadMovementGuardConfig } from "./qc/HeadMovementGuard";

document.querySelector<HTMLDivElement>("#app")!.innerHTML = `
<section class="shell">
  <nav class="steps" aria-label="Demo progress"><span class="step active" id="step-camera">1 Camera</span><span class="step" id="step-calibration">2 Calibration</span><span class="step" id="step-validation">3 Validation</span><span class="step" id="step-demo">4 Demo</span></nav>
  <header><p class="eyebrow">OpenEyeTrack browser demo</p><h1>Eye tracking from your webcam</h1><p>Set up your camera, calibrate your gaze, check data quality, then try the live tracker. Video stays on this device.</p></header>
  <section class="setup-card" id="camera-check"><div><h2>Camera check</h2><p>Centre your face, keep both eyes visible and use even lighting. Once tracking is stable, continue to calibration.</p></div><div class="check-list"><div><span id="check-face" class="check-dot"></span><b>Face detected</b></div><div><span id="check-eyes" class="check-dot"></span><b>Eye features available</b></div><div><span id="check-fps" class="check-dot"></span><b id="check-fps-label">Camera frame rate</b></div></div><button id="continue-calibration" class="primary" disabled>Continue to calibration</button></section>
  <div class="viewer"><video id="webcam" autoplay muted playsinline></video><canvas id="landmarks"></canvas><div class="placeholder" id="placeholder">Camera preview</div></div>
  <div class="controls"><button id="start" class="primary">Start camera</button><button id="calibrate" disabled>Calibrate gaze</button><button id="validate" disabled>Validate</button><button id="demo" disabled>Try live gaze demo</button><button id="record" disabled>Start recording</button><button id="export" disabled>Export CSV</button><button id="stop" disabled>Stop camera</button></div>
  <details class="research-settings"><summary>Advanced / research settings</summary><label class="toggle"><input id="show-values" type="checkbox" checked /> Show live landmark values</label><h3>Recording QC</h3><div class="settings-grid"><label><span>Head movement guard</span><input id="head-guard" type="checkbox" checked /></label><label>Max position shift (% frame)<input id="head-xy" type="number" min="1" max="30" step="1" value="6" /></label><label>Max distance-proxy shift (% frame)<input id="head-z" type="number" min="1" max="30" step="1" value="12" /></label><label>Max head angle change (°)<input id="head-angle" type="number" min="2" max="45" step="1" value="12" /></label><label>Grace period (ms)<input id="head-grace" type="number" min="100" max="5000" step="100" value="700" /></label></div></details>
  <pre id="status">Ready. Face landmark inference runs locally in the browser.</pre>
</section>
<div id="calibration-setup" class="calibration-screen" hidden><div class="calibration-card">
  <p class="eyebrow">Step 2 of 4</p><h2>Calibrate your gaze</h2>
  <p>For the best calibration, prepare your position before you start:</p>
  <ul class="calibration-instructions">
    <li>Sit comfortably with your head near the centre of the camera image.</li>
    <li>Keep your face clearly visible and both eyes open.</li>
    <li>If possible, remove glasses, especially if they create reflections or glare.</li>
    <li>Avoid sitting with a bright window, lamp or other strong light behind you.</li>
    <li>Use soft, even lighting on your face and avoid strong shadows.</li>
    <li>Keep your head as still as is comfortable during calibration.</li>
    <li>Look directly at each target with your eyes and keep looking at it until it moves.</li>
  </ul>
  <p class="calibration-note"><strong>During calibration:</strong> follow only the target. The calibration screen will hide all other controls.</p>
  <details class="calibration-advanced"><summary>Advanced calibration settings</summary><div class="settings-grid">
    <label>Gaze algorithm<select id="gaze-model"><option value="linear">Linear ridge</option><option value="polynomial">Polynomial ridge</option><option value="rbf" selected>RBF kernel regression</option><option value="knn">k-nearest neighbours</option></select></label>
    <label>Number of points<select id="cal-points"><option value="5">5 points</option><option value="9">9 points</option><option value="13" selected>13 points</option></select></label>
    <label>Repetitions<input id="cal-repetitions" type="number" min="1" max="5" value="2" /></label>
    <label>Settle time (ms)<input id="cal-settle" type="number" min="200" max="3000" step="100" value="700" /></label>
    <label>Sampling time (ms)<input id="cal-sample" type="number" min="300" max="5000" step="100" value="900" /></label>
    <label>Target size (px)<input id="target-size" type="number" min="8" max="100" step="2" value="34" /></label>
    <label>Target figure<select id="target-shape"><option value="bullseye" selected>Bullseye</option><option value="circle">Circle</option><option value="dot">Dot</option><option value="cross">Cross</option></select></label>
    <label>Target colour<input id="target-color" type="color" value="#172033" /></label>
    <label>Ridge / regularisation<input id="model-ridge" type="number" min="0.000001" max="10" step="0.001" value="0.05" /></label>
    <label>RBF gamma<input id="model-gamma" type="number" min="0.001" max="10" step="0.05" value="0.15" /></label>
    <label>k for kNN<input id="model-k" type="number" min="1" max="15" value="3" /></label>
  </div>
  <label class="toggle"><input id="cal-randomize" type="checkbox" /> Randomize target order</label>
  <label class="toggle"><input id="cal-adaptive" type="checkbox" checked /> Accumulate previous calibration and use validation to choose extra targets</label>
  <p class="calibration-note">Adaptive recalibration retains the previous calibration observations, adds new observations, and uses the previous validation error map to place extra targets while preserving broad screen coverage.</p>
  </details><div class="calibration-actions"><button id="cancel-calibration">Back to main page</button><button id="start-calibration" class="primary">Start calibration</button></div>
</div></div>
<div id="calibration-stage" class="calibration-stage" hidden><div id="calibration-target" class="calibration-target" hidden><span></span></div></div>
<div id="post-calibration" class="modal-screen" hidden><div class="results-card"><p class="eyebrow">Calibration complete</p><h2>Ready to validate</h2><p>Your gaze model has been calibrated. Validation checks how accurately and consistently it follows known points on the screen.</p><div class="calibration-actions"><button id="calibration-home">Back to main page</button><button id="calibration-validate" class="primary">Continue to validation</button></div></div></div>
<div id="gaze-dot" class="gaze-dot" hidden></div>
<div id="validation-results" class="modal-screen" hidden><div class="results-card"><p class="eyebrow">Step 3 of 4</p><h2>Validation complete</h2><div class="metric-grid"><div><span>Mean error</span><strong id="metric-mean">—</strong></div><div><span>Median error</span><strong id="metric-median">—</strong></div><div><span>RMS-S2S</span><strong id="metric-precision">—</strong></div><div><span>Valid samples</span><strong id="metric-valid">—</strong></div></div><p class="muted">Validation measures the current model without refitting it.</p><div class="calibration-actions"><button id="results-recalibrate">Recalibrate</button><button id="results-demo" class="primary">Continue to demo</button></div></div></div>
<div id="demo-screen" class="demo-screen" hidden><div class="demo-top"><div><p class="eyebrow">Step 4 of 4</p><h2>Live gaze demo</h2></div><button id="exit-demo">Exit demo</button></div><div class="demo-content"><h3>Look around this page</h3><p>The ring shows the current filtered gaze estimate. Try looking at the cards, headings and corners of the screen.</p><div class="demo-grid"><article><b>Top left</b><p>Focus here for a moment.</p></article><article><b>Top right</b><p>Then move your eyes here.</p></article><article><b>Bottom left</b><p>Notice how the gaze estimate follows.</p></article><article><b>Bottom right</b><p>Head movement can affect accuracy.</p></article></div></div></div>
<div id="head-warning" class="warning-screen" hidden><div class="warning-card"><h2>Recording paused</h2><p id="head-warning-text"></p><p>Return to your original comfortable head position, then start the recording again.</p><button id="dismiss-head-warning">Continue</button></div></div>`;

const q=<T extends Element>(s:string)=>document.querySelector<T>(s)!;
const video=q<HTMLVideoElement>("#webcam"),canvas=q<HTMLCanvasElement>("#landmarks"),status=q<HTMLPreElement>("#status"),startButton=q<HTMLButtonElement>("#start"),stopButton=q<HTMLButtonElement>("#stop"),recordButton=q<HTMLButtonElement>("#record"),exportButton=q<HTMLButtonElement>("#export"),placeholder=q<HTMLDivElement>("#placeholder"),showValues=q<HTMLInputElement>("#show-values"),calibrateButton=q<HTMLButtonElement>("#calibrate"),validateButton=q<HTMLButtonElement>("#validate"),calibrationSetup=q<HTMLDivElement>("#calibration-setup"),calibrationStage=q<HTMLDivElement>("#calibration-stage"),calibrationTarget=q<HTMLDivElement>("#calibration-target"),gazeDot=q<HTMLDivElement>("#gaze-dot"),startCalibrationButton=q<HTMLButtonElement>("#start-calibration"),cancelCalibrationButton=q<HTMLButtonElement>("#cancel-calibration"),pointsInput=q<HTMLSelectElement>("#cal-points"),settleInput=q<HTMLInputElement>("#cal-settle"),sampleInput=q<HTMLInputElement>("#cal-sample"),repetitionsInput=q<HTMLInputElement>("#cal-repetitions"),randomizeInput=q<HTMLInputElement>("#cal-randomize"),adaptiveInput=q<HTMLInputElement>("#cal-adaptive"),modelInput=q<HTMLSelectElement>("#gaze-model"),ridgeInput=q<HTMLInputElement>("#model-ridge"),gammaInput=q<HTMLInputElement>("#model-gamma"),kInput=q<HTMLInputElement>("#model-k"),targetSizeInput=q<HTMLInputElement>("#target-size"),targetShapeInput=q<HTMLSelectElement>("#target-shape"),targetColorInput=q<HTMLInputElement>("#target-color"),headGuardInput=q<HTMLInputElement>("#head-guard"),headXYInput=q<HTMLInputElement>("#head-xy"),headZInput=q<HTMLInputElement>("#head-z"),headAngleInput=q<HTMLInputElement>("#head-angle"),headGraceInput=q<HTMLInputElement>("#head-grace"),headWarning=q<HTMLDivElement>("#head-warning"),headWarningText=q<HTMLParagraphElement>("#head-warning-text"),dismissHeadWarning=q<HTMLButtonElement>("#dismiss-head-warning"),continueCalibration=q<HTMLButtonElement>("#continue-calibration"),demoButton=q<HTMLButtonElement>("#demo"),validationResults=q<HTMLDivElement>("#validation-results"),resultsRecalibrate=q<HTMLButtonElement>("#results-recalibrate"),resultsDemo=q<HTMLButtonElement>("#results-demo"),demoScreen=q<HTMLDivElement>("#demo-screen"),exitDemo=q<HTMLButtonElement>("#exit-demo"),checkFace=q<HTMLSpanElement>("#check-face"),checkEyes=q<HTMLSpanElement>("#check-eyes"),checkFps=q<HTMLSpanElement>("#check-fps"),checkFpsLabel=q<HTMLElement>("#check-fps-label"),metricMean=q<HTMLElement>("#metric-mean"),metricMedian=q<HTMLElement>("#metric-median"),metricPrecision=q<HTMLElement>("#metric-precision"),metricValid=q<HTMLElement>("#metric-valid"),postCalibration=q<HTMLDivElement>("#post-calibration"),calibrationHome=q<HTMLButtonElement>("#calibration-home"),calibrationValidate=q<HTMLButtonElement>("#calibration-validate");

const tracker=new OpenEyeTrack(video),faceTracker=new FaceFeatureTracker(),overlay=new LandmarkOverlay(canvas),calibration=new CalibrationController(calibrationTarget,readCalibrationConfig()),gazeFilter=new AdaptiveGazeFilter(),headGuard=new HeadMovementGuard(readHeadGuardConfig());
let recording=false,lastRecording:EyeTrackingSample[]=[],statusTimer:number|null=null,detectionAnimation:number|null=null,detectedFaces=0,latestFeatures:EyeHeadFeatures|null=null,calibrationActive=false;

startButton.onclick=async()=>{try{status.textContent="Loading face landmark model…";await faceTracker.initialize();status.textContent="Requesting camera permission…";const settings=await tracker.start();placeholder.hidden=true;startButton.disabled=true;stopButton.disabled=false;recordButton.disabled=false;calibrateButton.disabled=false;runLandmarks();updateStatus(settings);statusTimer=window.setInterval(()=>updateStatus(settings),500);}catch(e){status.textContent=`Startup error: ${e instanceof Error?e.message:String(e)}`;}};
recordButton.onclick=()=>recording?finishRecording("recording_stop"):beginRecording();
stopButton.onclick=()=>{if(recording)finishRecording("recording_stop");if(statusTimer!==null)clearInterval(statusTimer);if(detectionAnimation!==null)cancelAnimationFrame(detectionAnimation);faceTracker.close();overlay.clear();tracker.stop();gazeFilter.reset();headGuard.reset();placeholder.hidden=false;startButton.disabled=false;stopButton.disabled=true;recordButton.disabled=true;calibrateButton.disabled=true;validateButton.disabled=true;gazeDot.hidden=true;exportButton.disabled=!lastRecording.length;status.textContent="Camera stopped.";};
exportButton.onclick=()=>downloadCsv(lastRecording);
calibrateButton.onclick=()=>openCalibration();
continueCalibration.onclick=()=>openCalibration();
demoButton.onclick=()=>openDemo();
resultsDemo.onclick=()=>{validationResults.hidden=true;openDemo();};
resultsRecalibrate.onclick=()=>{validationResults.hidden=true;openCalibration();};
exitDemo.onclick=()=>{demoScreen.hidden=true;gazeDot.hidden=false;};
cancelCalibrationButton.onclick=()=>{calibrationSetup.hidden=true;setStep("camera");};
calibrationHome.onclick=()=>{postCalibration.hidden=true;setStep("camera");};
calibrationValidate.onclick=()=>{postCalibration.hidden=true;validateButton.click();};
dismissHeadWarning.onclick=()=>{headWarning.hidden=true;};

startCalibrationButton.onclick=async()=>{const config=readCalibrationConfig();calibration.setConfig(config);calibrationSetup.hidden=true;calibrationStage.hidden=false;calibrationActive=true;setBusy(true);gazeFilter.reset();try{const summary=await calibration.calibrate(()=>latestFeatures);tracker.setCalibrationSummary(summary);validateButton.disabled=false;demoButton.disabled=false;setStep("validation");postCalibration.hidden=false;status.textContent=`Calibration complete: ${summary.config.model.type} | ${summary.observations} total observations (${summary.newObservations} new + ${summary.retainedObservations} retained) | adaptive targets: ${summary.adaptiveUsed?"yes":"no"}.`;}catch(e){status.textContent=`Calibration error: ${e instanceof Error?e.message:String(e)}`;}finally{calibrationActive=false;calibrationStage.hidden=true;gazeFilter.reset();setBusy(false);}};
validateButton.onclick=async()=>{calibrationStage.hidden=false;calibrationActive=true;gazeDot.hidden=true;setBusy(true);gazeFilter.reset();try{const r=await calibration.validate(()=>latestFeatures);tracker.setValidationResult(r);metricMean.textContent=`${r.meanPx.toFixed(0)} px`;metricMedian.textContent=`${r.medianPx.toFixed(0)} px`;metricPrecision.textContent=`${r.precisionRmsS2SPx.toFixed(1)} px`;metricValid.textContent=`${((1-r.dataLoss)*100).toFixed(0)}%`;validationResults.hidden=false;demoButton.disabled=false;setStep("demo");const model=calibration.calibrationSummary?.config.model.type??"model";status.textContent=`Validation (${model}): mean ${r.meanPx.toFixed(0)} px | median ${r.medianPx.toFixed(0)} px | RMSE ${r.rmsePx.toFixed(0)} px\nPrecision: RMS-S2S ${r.precisionRmsS2SPx.toFixed(1)} px | spatial SD ${r.precisionSdPx.toFixed(1)} px | data loss ${(r.dataLoss*100).toFixed(1)}%\nValidation did not refit the active gaze estimator. Its error map was saved only for a future adaptive recalibration.`;}catch(e){status.textContent=`Validation error: ${e instanceof Error?e.message:String(e)}`;}finally{calibrationActive=false;calibrationStage.hidden=true;gazeFilter.reset();setBusy(false);}};

function beginRecording(){headGuard.setConfig(readHeadGuardConfig());headGuard.start(latestFeatures);tracker.startRecording();tracker.setTrial("test");tracker.mark("recording_start");recording=true;recordButton.textContent="Stop recording";exportButton.disabled=true;}
function finishRecording(event:string){tracker.mark(event);lastRecording=tracker.stopRecording();recording=false;recordButton.textContent="Start recording";exportButton.disabled=!lastRecording.length;headGuard.reset();}
function interruptForHeadMovement(reason:string){if(!recording)return;finishRecording("head_movement_interrupt");headWarningText.textContent=`Recording stopped because ${reason}.`;headWarning.hidden=false;status.textContent=`Recording interrupted: ${reason}. ${lastRecording.length} samples retained and available for export.`;}

function runLandmarks(){overlay.resizeTo(video);const result=faceTracker.detect(video,performance.now());if(result){detectedFaces=result.faceLandmarks.length;const face=result.faceLandmarks[0];if(face){const matrix=result.facialTransformationMatrixes?.[0]?.data;latestFeatures=extractEyeHeadFeatures(face,matrix?Array.from(matrix):undefined);tracker.setFeatures(latestFeatures);if(recording&&latestFeatures){const violation=headGuard.check(latestFeatures);if(violation)interruptForHeadMovement(violation.reason);}const raw=latestFeatures?calibration.model.predict(latestFeatures):null,filtered=raw?gazeFilter.filter(raw):null;tracker.setGaze(raw,filtered);if(filtered&&!calibrationActive&&calibrationSetup.hidden&&headWarning.hidden){gazeDot.hidden=false;gazeDot.style.left=`${Math.max(0,Math.min(innerWidth,filtered.x))}px`;gazeDot.style.top=`${Math.max(0,Math.min(innerHeight,filtered.y))}px`;}else gazeDot.hidden=true;overlay.draw(face,latestFeatures,showValues.checked);}else{latestFeatures=null;tracker.setFeatures(null);tracker.setGaze(null);gazeFilter.reset();gazeDot.hidden=true;overlay.clear();}}detectionAnimation=requestAnimationFrame(runLandmarks);}
function openCalibration(){calibrationSetup.hidden=false;gazeDot.hidden=true;setStep("calibration");}
function openDemo(){demoScreen.hidden=false;gazeDot.hidden=false;setStep("demo");}
function setStep(name:"camera"|"calibration"|"validation"|"demo"){for(const n of ["camera","calibration","validation","demo"])q<HTMLElement>(`#step-${n}`).classList.toggle("active",n===name);}
function updateCameraChecks(){const fps=tracker.getObservedFps();const faceOk=detectedFaces===1,eyesOk=latestFeatures!==null,fpsOk=(fps??0)>=20;checkFace.classList.toggle("ok",faceOk);checkEyes.classList.toggle("ok",eyesOk);checkFps.classList.toggle("ok",fpsOk);checkFpsLabel.textContent=fps?`Camera frame rate (${fps.toFixed(0)} FPS)`:"Camera frame rate";continueCalibration.disabled=!(faceOk&&eyesOk&&fpsOk);}
function updateStatus(settings:MediaTrackSettings){updateCameraChecks();if(calibrationActive||!calibrationSetup.hidden||!headWarning.hidden)return;const fps=tracker.getObservedFps(),model=calibration.calibrationSummary?.config.model.type;status.textContent=["Camera running",`Resolution: ${settings.width??"?"} × ${settings.height??"?"}`,`Observed frame rate: ${fps?.toFixed(1)??"measuring…"} FPS`,`Faces detected: ${detectedFaces}`,`Gaze model: ${model??"not calibrated"}`,`Calibration memory: ${calibration.hasCalibrationMemory?"available":"none"}`,`Head movement guard: ${headGuardInput.checked?"on":"off"}`,`Samples recorded: ${tracker.getSampleCount()}`].join("\n");}
function readCalibrationConfig():CalibrationConfig{return{points:Number(pointsInput?.value??13)as CalibrationPointCount,settleMs:Number(settleInput?.value??700),sampleMs:Number(sampleInput?.value??900),repetitions:Number(repetitionsInput?.value??2),randomize:randomizeInput?.checked??false,adaptiveTargets:adaptiveInput?.checked??true,target:{sizePx:Number(targetSizeInput?.value??34),shape:(targetShapeInput?.value??"bullseye")as TargetShape,color:targetColorInput?.value??"#172033"},model:{type:(modelInput?.value??"rbf")as GazeModelType,ridge:Number(ridgeInput?.value??.05),rbfGamma:Number(gammaInput?.value??.15),knnK:Number(kInput?.value??3)}};}
function readHeadGuardConfig():HeadMovementGuardConfig{return{enabled:headGuardInput?.checked??true,maxXY:Number(headXYInput?.value??6)/100,maxZ:Number(headZInput?.value??12)/100,maxAngleDeg:Number(headAngleInput?.value??12),graceMs:Number(headGraceInput?.value??700)};}
function downloadCsv(samples:EyeTrackingSample[]){if(!samples.length)return;const columns=Object.keys(samples[0])as(keyof EyeTrackingSample)[],rows=samples.map(s=>columns.map(c=>csvCell(s[c])).join(",")),csv=[columns.join(","),...rows].join("\n"),blob=new Blob([csv],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`openeyetrack-${new Date().toISOString().replaceAll(":","-")}.csv`;link.click();URL.revokeObjectURL(url);}
function csvCell(value:unknown){if(value===null||value===undefined)return"";const text=String(value);return /[,"\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text;}
function setBusy(busy:boolean){calibrateButton.disabled=busy;validateButton.disabled=busy||!calibration.model.calibrated;recordButton.disabled=busy;}
