import type { EyeHeadFeatures } from "../features/EyeHeadFeatures";
import type { CalibrationObservation, GazePrediction } from "./LinearGazeModel";
import { createGazeEstimator, type GazeModelConfig } from "./GazeModels";
import type { GazeEstimator } from "../gaze/GazeEstimator";
import { CalibrationMemory } from "./CalibrationMemory";
import { buildHeadPoseReference, type HeadPoseReference } from "../qc/CalibrationHeadPose";
export type CalibrationPointCount = 5 | 9 | 13;
export type TargetShape = "bullseye" | "circle" | "dot" | "cross";
export interface CalibrationTargetConfig { sizePx:number; shape:TargetShape; color:string; }
export interface CalibrationConfig { points:CalibrationPointCount; settleMs:number; sampleMs:number; repetitions:number; randomize:boolean; adaptiveTargets:boolean; target:CalibrationTargetConfig; model:GazeModelConfig; }
export interface CalibrationSummary { id:string; config:CalibrationConfig; observations:number; newObservations:number; retainedObservations:number; targetsCompleted:number; samplesCollected:number; adaptiveUsed:boolean; headPoseReference:HeadPoseReference|null; }
export interface ValidationPointResult { targetX:number; targetY:number; samplesExpected:number; samplesValid:number; accuracyPx:number; precisionRmsS2SPx:number; precisionSdPx:number; }
export interface ValidationResult { meanPx:number; medianPx:number; rmsePx:number; precisionRmsS2SPx:number; precisionSdPx:number; dataLoss:number; points:number; pointResults:ValidationPointResult[]; }
const POINT_SETS:Record<CalibrationPointCount,readonly(readonly[number,number])[]>={5:[[.5,.5],[.12,.12],[.88,.12],[.12,.88],[.88,.88]],9:[[.12,.12],[.5,.12],[.88,.12],[.12,.5],[.5,.5],[.88,.5],[.12,.88],[.5,.88],[.88,.88]],13:[[.12,.12],[.5,.12],[.88,.12],[.12,.5],[.5,.5],[.88,.5],[.12,.88],[.5,.88],[.88,.88],[.31,.31],[.69,.31],[.31,.69],[.69,.69]]};
const FEATURE_KEYS:(keyof EyeHeadFeatures)[]=["leftIrisX","leftIrisY","rightIrisX","rightIrisY","leftRelX","leftRelY","rightRelX","rightRelY","leftIrisDiameter","rightIrisDiameter","headX","headY","headZ","headYaw","headPitch","headRoll"];
export class CalibrationController {
  model:GazeEstimator;private config:CalibrationConfig;private lastSummary:CalibrationSummary|null=null;private memory=new CalibrationMemory();private activePoints:readonly(readonly[number,number])[]=POINT_SETS[13];private accumulatedObservations:CalibrationObservation[]=[];private accumulatedModelKey="";
  constructor(private readonly target:HTMLElement,config:CalibrationConfig){this.config=cloneConfig(config);this.model=createGazeEstimator(this.config.model);this.accumulatedModelKey=modelKey(this.config.model);this.applyTargetStyle();}
  setConfig(config:CalibrationConfig){const changed=JSON.stringify(config.model)!==JSON.stringify(this.config.model);this.config=cloneConfig(config);if(changed){this.model=createGazeEstimator(this.config.model);this.accumulatedObservations=[];this.accumulatedModelKey=modelKey(this.config.model);}this.applyTargetStyle();}
  get pointCount(){return this.activePoints.length;}get calibrationSummary(){return this.lastSummary;}get hasCalibrationMemory(){return this.memory.has(this.config.model.type);}
  clearCalibrationMemory(){this.memory.clear();this.accumulatedObservations=[];this.lastSummary=null;}
  async calibrate(getFeatures:()=>EyeHeadFeatures|null):Promise<CalibrationSummary>{
    const key=modelKey(this.config.model);if(key!==this.accumulatedModelKey){this.accumulatedObservations=[];this.accumulatedModelKey=key;}
    const adaptive=this.config.adaptiveTargets?this.memory.adaptivePoints(this.config.model.type,this.config.points):null;this.activePoints=adaptive??POINT_SETS[this.config.points];
    const newObservations:CalibrationObservation[]=[];const calibrationFeatureSamples:EyeHeadFeatures[]=[];let samplesCollected=0;const sequence=this.calibrationSequence();this.target.hidden=false;
    try{for(const[nx,ny]of sequence){this.place(nx,ny);await wait(this.config.settleMs);const samples:EyeHeadFeatures[]=[];const end=performance.now()+this.config.sampleMs;while(performance.now()<end){const f=getFeatures();if(f){const copy={...f};samples.push(copy);calibrationFeatureSamples.push(copy);samplesCollected++;}await wait(33);}if(samples.length)newObservations.push({targetX:nx*innerWidth,targetY:ny*innerHeight,features:medianFeatures(samples)});}}finally{this.target.hidden=true;}
    const retainPrevious=this.config.adaptiveTargets&&this.accumulatedObservations.length>0;const retained=retainPrevious?this.accumulatedObservations:[];const combined=[...retained,...newObservations];const candidate=createGazeEstimator(this.config.model);await candidate.fit(combined);this.model=candidate;this.accumulatedObservations=combined;
    this.lastSummary={id:`cal-${Date.now()}`,config:cloneConfig(this.config),observations:combined.length,newObservations:newObservations.length,retainedObservations:retained.length,targetsCompleted:sequence.length,samplesCollected,adaptiveUsed:adaptive!==null,headPoseReference:buildHeadPoseReference(calibrationFeatureSamples)};return this.lastSummary;
  }
  async validate(getFeatures:()=>EyeHeadFeatures|null):Promise<ValidationResult>{const validationPoints=POINT_SETS[this.config.points];const results:ValidationPointResult[]=[];let totalExpected=0,totalValid=0;this.target.hidden=false;try{for(const[nx,ny]of validationPoints){this.place(nx,ny);await wait(this.config.settleMs);const targetX=nx*innerWidth,targetY=ny*innerHeight,predictions:GazePrediction[]=[];const expected=Math.max(1,Math.round(this.config.sampleMs/33));const end=performance.now()+this.config.sampleMs;while(performance.now()<end){const f=getFeatures(),p=f?this.model.predict(f):null;if(p&&Number.isFinite(p.x)&&Number.isFinite(p.y))predictions.push(p);await wait(33);}totalExpected+=expected;totalValid+=predictions.length;if(predictions.length){const x=median(predictions.map(p=>p.x)),y=median(predictions.map(p=>p.y));results.push({targetX,targetY,samplesExpected:expected,samplesValid:predictions.length,accuracyPx:Math.hypot(x-targetX,y-targetY),precisionRmsS2SPx:rmsS2S(predictions),precisionSdPx:spatialSd(predictions)});}}}finally{this.target.hidden=true;}if(!results.length)throw new Error("No valid gaze samples were collected during validation.");this.memory.save(this.config.model.type,results);const errors=results.map(r=>r.accuracyPx);return{meanPx:mean(errors),medianPx:median(errors),rmsePx:Math.sqrt(mean(errors.map(e=>e*e))),precisionRmsS2SPx:mean(results.map(r=>r.precisionRmsS2SPx)),precisionSdPx:mean(results.map(r=>r.precisionSdPx)),dataLoss:Math.max(0,1-totalValid/totalExpected),points:results.length,pointResults:results};}
  private calibrationSequence(){const sequence:(readonly[number,number])[]=[];for(let r=0;r<this.config.repetitions;r++){const p=[...this.activePoints];if(this.config.randomize)shuffle(p);sequence.push(...p);}return sequence;}
  private place(nx:number,ny:number){this.target.style.left=`${nx*100}%`;this.target.style.top=`${ny*100}%`;}
  private applyTargetStyle(){this.target.dataset.shape=this.config.target.shape;this.target.style.setProperty("--target-size",`${this.config.target.sizePx}px`);this.target.style.setProperty("--target-color",this.config.target.color);}
}
function modelKey(c:GazeModelConfig){return JSON.stringify(c);}
function cloneConfig(c:CalibrationConfig):CalibrationConfig{return{...c,target:{...c.target},model:{...c.model}};}
function medianFeatures(samples:EyeHeadFeatures[]):EyeHeadFeatures{const out={}as EyeHeadFeatures;for(const key of FEATURE_KEYS){const vals=samples.map(s=>s[key]).filter((v):v is number=>typeof v==="number"&&Number.isFinite(v));(out as unknown as Record<string,number|null>)[key]=vals.length?median(vals):null;}return out;}
function rmsS2S(p:GazePrediction[]){if(p.length<2)return 0;return Math.sqrt(mean(p.slice(1).map((q,i)=>(q.x-p[i].x)**2+(q.y-p[i].y)**2)));}function spatialSd(p:GazePrediction[]){const mx=mean(p.map(q=>q.x)),my=mean(p.map(q=>q.y));return Math.sqrt(mean(p.map(q=>(q.x-mx)**2+(q.y-my)**2)));}function mean(v:number[]){return v.reduce((a,b)=>a+b,0)/v.length;}function wait(ms:number){return new Promise<void>(r=>setTimeout(r,ms));}function median(v:number[]){const s=[...v].sort((a,b)=>a-b),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2;}function shuffle<T>(v:T[]){for(let i=v.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[v[i],v[j]]=[v[j],v[i]];}}

